### ISSUE TITLE
Cannot add user ID via UI with SQL auth - TypeError: post() missing 1 required positional argument: 'user_id'

### ISSUE THREAD

**Issue by hkelley** [f0cker/crackq#39]
**Describe the bug**
Cannot add user ID via UI with SQL auth

**To Reproduce**

![image](https://github.com/f0cker/crackq/assets/8828244/eb7d5274-31ed-46f0-8c05-cc4539f79881)
![image](https://github.com/f0cker/crackq/assets/8828244/bfc1036d-6834-4e06-8f2f-6d1734d1eef5)

**Expected behavior**
SQL-based user ID is created

**Debug output**
```
ERROR    app.py:1892 log_exception 2023-07-31 19:51:49,207 Exception on /api/admin/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/crackq/build/crackq/cq_api.py", line 390, in wrap
    return func(args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
TypeError: post() missing 1 required positional argument: 'user_id'

```

**Comment by f0cker** [comment]
I don't have this issue. I fixed it before moving from dev, I think your JS gui might be cached from using the dev branch. Can you check your browser dev tools to see if you're loading /js/app.dcad8ee7.js? You may have an older version there.

**Comment by f0cker** [comment]
Also I'm not sure how you're using python3.6, it should be 3.8 now. Which build did you use docker/nvidia/centos maybe?

**Comment by hkelley** [comment]
My UI loads /js/app.e79626a4.js,  regardless of what browser I use.

Yes, I'm using NVIDIA GPUs on centos.

I'm not very Docker savvy - how do I get up to Python 3.8?   Could this Python version also explain these `_pickle.UnpicklingError: invalid load key, '{'.` issues, which have reappeared?
```
ERROR    app.py:1892 log_exception 2023-08-01 10:36:55,358 Exception on /api/queuing/all [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/opt/crackq/build/crackq/cq_api.py", line 840, in get
    cur_list = started.get_job_ids()
  File "/usr/local/lib/python3.6/site-packages/rq/registry.py", line 97, in get_job_ids
    self.cleanup()
  File "/usr/local/lib/python3.6/site-packages/rq/registry.py", line 139, in cleanup
    connection=self.connection)
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 309, in fetch
    job.refresh()
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 541, in refresh
    self.restore(data)
  File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 517, in restore
    self.meta = self.serializer.loads(obj.get('meta')) if obj.get('meta') else {}
_pickle.UnpicklingError: invalid load key, '{'.

```

**Comment by f0cker** [comment]
Ah I haven't updated the CentOS build, since it's now EoL I believe. Use docker/nvidia/ubuntu build instead. For the GUI, you should have app.dcad8ee7.js  in your ./dist/js/ directory. If you're building from a directory where you had a previous install, you may need to remove the ./build directory as well.

**Comment by f0cker** [comment]
Yup that'll be the problem, can you modify nvidia-centos to nvidia-ubuntu and check if it runs properly? I don't have an nvidia box setup to test at the moment. I'll push the change to master if it works OK. If not I'll have to setup a cloud vm to debug.

**Comment by hkelley** [comment]
Starts up and renders the UI but seems to fail when submitting a job.   I'll go back to the nvidia-centos image for now.
```
INFO     run_hashcat.py:116 runner 2023-08-01 16:22:29,933 Running hashcat
ERROR    run_hashcat.py:188 runner 2023-08-01 16:22:29,960 Speed check failed: RuntimeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 1418, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1222, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1259, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/opt/crackq/build/crackq/run_hashcat.py", line 988, in show_speed
    hcat = runner(hash_file=hash_file, mask=mask,
  File "/opt/crackq/build/crackq/run_hashcat.py", line 159, in runner
    hc.hashcat_session_execute()
SystemError: <method 'hashcat_session_execute' of 'pyhashcat.hashcat' objects> returned a result with an error set
```

![image](https://github.com/f0cker/crackq/assets/8828244/e7270039-8cd4-4e6c-8daa-60774708610d)
