### ISSUE TITLE
Error with Created Jobs Nvidia 

### ISSUE THREAD

**Issue by CarbonTrinity** [f0cker/crackq#43]
**Describe the bug**
Hey, When creating a new job using 0.1.2 and Ubuntu + NVIDIA the job is scheduled but fails immediately afterwards. A look at the console error message lists the Speed check failed error entry. This affects both with/without brain enabled.  Ive tried launching new and previously cracked jobs. The issue doesn't seem to affect opencl, which works fine.  So Im thinking its potentially an issue related to hashcat/nvidia. The issue mostly seems to come from run_hashcat.py i think. 

**Version**
```
root@localhost:/opt/crackq-0.1.2# uname -a
Linux localhost 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Running instances**
```
root@localhost:/opt/crackq-0.1.2/build# docker ps
CONTAINER ID   IMAGE           COMMAND                  CREATED          STATUS          PORTS                                           NAMES
50c58e6fa8af   nginx-crackq    "/docker-entrypoint.…"   28 seconds ago   Up 27 seconds   80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx
34c0de1d67a7   nvidia-ubuntu   "/opt/nvidia/nvidia_…"   29 seconds ago   Up 28 seconds   6379/tcp, 8081/tcp, 127.0.0.1:8080->8080/tcp    crackq
e734a0eb4655   redis:latest    "docker-entrypoint.s…"   29 seconds ago   Up 28 seconds   127.0.0.1:6379->6379/tcp
```
**Nvidia SMI**
```

root@localhost:/opt/crackq-0.1.2/build# nvidia-smi
Wed Jan 17 11:27:05 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 50%   31C    P8    14W / 250W |     14MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 51%   28C    P8    14W / 250W |      5MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 50%   25C    P8    13W / 250W |      5MiB /  4043MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1083      G   /usr/lib/xorg/Xorg                  7MiB |
|    0   N/A  N/A      1693      G   /usr/bin/gnome-shell                2MiB |
|    1   N/A  N/A      1083      G   /usr/lib/xorg/Xorg                  3MiB |
|    2   N/A  N/A      1083      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+

```

**Crash Error - Brain Enabled**
```
root@localhost:/opt/crackq-0.1.2/build# screen -r PW
crackq    | 00:30:20 speed_check: crackq.run_hashcat.show_speed(attack_mode=0, brain=True, hash_file='/var/crackq/logs/4108b8eab7ef475093bd9f8e4190a9a4.hashes', hash_mode=100, mask='?a?a?a?a?a?a', name='Example4', pot_path='/var/crackq/logs/crackq.pot', session='4108b8eab7ef475093bd9f8e4190a9a4', speed_session='4108b8eab7ef475093bd9f8e4190a9a4_speed', username=False, wordlist2=None, wordlist='/var/crackq/files/rockyou.txt.gz') (4108b8eab7ef475093bd9f8e4190a9a4_speed)
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:21,096 Reading from config file /var/crackq/files/crackq.conf
crackq    | [nltk_data] Downloading package wordnet to /home/crackq/nltk_data...
crackq    | [nltk_data]   Package wordnet is already up-to-date!
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:21,272 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:21,307 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     schemas.py:1260 include_schema 2024-01-17 00:30:21,557 Resource 'XMLSchema.xsd' is already loaded
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:23,147 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     run_hashcat.py:116 runner 2024-01-17 00:30:23,168 Running hashcat
crackq    | INFO     crackqueue.py:47 q_add 2024-01-17 00:30:23,513 Adding task to job queue: 4108b8eab7ef475093bd9f8e4190a9a4
crackq    | 00:30:23 default: crackq.run_hashcat.hc_worker(attack_mode=0, brain=True, hash_file='/var/crackq/logs/4108b8eab7ef475093bd9f8e4190a9a4.hashes', hash_mode=100, increment=False, increment_max=None, increment_min=None, mask=None, mask_file=False, name='Example4', outfile='/var/crackq/logs/4108b8eab7ef475093bd9f8e4190a9a4.cracked', pot_path='/var/crackq/logs/crackq.pot', potcheck=False, restore=0, rules=[], session='4108b8eab7ef475093bd9f8e4190a9a4', username=False, wordlist2=None, wordlist='/var/crackq/files/rockyou.txt.gz') (4108b8eab7ef475093bd9f8e4190a9a4)
redis     | 1:M 17 Jan 2024 00:30:23.528 * 100 changes in 300 seconds. Saving...
redis     | 1:M 17 Jan 2024 00:30:23.529 * Background saving started by pid 21
nginx     | 10.255.255.10 - - [17/Jan/2024:00:30:23 +0000] "POST /api/add HTTP/1.1" 202 32 "https://192.168.1.1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
redis     | 21:C 17 Jan 2024 00:30:23.541 * DB saved on disk
redis     | 21:C 17 Jan 2024 00:30:23.543 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis     | 1:M 17 Jan 2024 00:30:23.630 * Background saving terminated with success
nginx     | 10.255.255.10 - - [17/Jan/2024:00:30:23 +0000] "GET /api/queuing/all HTTP/1.1" 200 375 "https://192.168.1.1/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:24,141 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     run_hashcat.py:116 runner 2024-01-17 00:30:24,171 Running hashcat
crackq    | [nltk_data] Downloading package wordnet to /home/crackq/nltk_data...
crackq    | [nltk_data]   Package wordnet is already up-to-date!
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:24,325 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:24,359 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     schemas.py:1260 include_schema 2024-01-17 00:30:24,610 Resource 'XMLSchema.xsd' is already loaded
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:30:26,198 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     run_hashcat.py:116 runner 2024-01-17 00:30:26,215 Running hashcat
crackq    | ERROR    run_hashcat.py:188 runner 2024-01-17 00:30:26,253 Speed check failed: RuntimeError
crackq    |
crackq    | The above exception was the direct cause of the following exception:
crackq    |
crackq    | Traceback (most recent call last):
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 1418, in perform_job
crackq    |     rv = job.perform()
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1222, in perform
crackq    |     self._result = self._execute()
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1259, in _execute
crackq    |     result = self.func(*self.args, **self.kwargs)
crackq    |   File "/opt/crackq/build/crackq/run_hashcat.py", line 988, in show_speed
crackq    |     hcat = runner(hash_file=hash_file, mask=mask,
crackq    |   File "/opt/crackq/build/crackq/run_hashcat.py", line 159, in runner
crackq    |     hc.hashcat_session_execute()
crackq    | SystemError: <method 'hashcat_session_execute' of 'pyhashcat.hashcat' objects> returned a result with an error set

```
**Crash Error - Brain Disabled**
```
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:32:00,424 Reading from config file /var/crackq/files/crackq.conf
crackq    | [nltk_data] Downloading package wordnet to /home/crackq/nltk_data...
crackq    | INFO     run_hashcat.py:116 runner 2024-01-17 00:32:00,468 Running hashcat
crackq    | [nltk_data]   Package wordnet is already up-to-date!
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:32:00,610 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:32:00,646 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     schemas.py:1260 include_schema 2024-01-17 00:32:00,903 Resource 'XMLSchema.xsd' is already loaded
crackq    | INFO     conf.py:18 hc_conf 2024-01-17 00:32:02,478 Reading from config file /var/crackq/files/crackq.conf
crackq    | INFO     run_hashcat.py:116 runner 2024-01-17 00:32:02,498 Running hashcat
crackq    | ERROR    run_hashcat.py:188 runner 2024-01-17 00:32:02,537 Speed check failed: RuntimeError
crackq    |
crackq    | The above exception was the direct cause of the following exception:
crackq    |
crackq    | Traceback (most recent call last):
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 1418, in perform_job
crackq    |     rv = job.perform()
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1222, in perform
crackq    |     self._result = self._execute()
crackq    |   File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 1259, in _execute
crackq    |     result = self.func(*self.args, **self.kwargs)
crackq    |   File "/opt/crackq/build/crackq/run_hashcat.py", line 988, in show_speed
crackq    |     hcat = runner(hash_file=hash_file, mask=mask,
crackq    |   File "/opt/crackq/build/crackq/run_hashcat.py", line 159, in runner
crackq    |     hc.hashcat_session_execute()
crackq    | SystemError: <method 'hashcat_session_execute' of 'pyhashcat.hashcat' objects> returned a result with an error set

```
**To Reproduce**
1. Login to web and queue new job. [Note ive tried both new and previously cracked jobs]
2. Enable/Disable brain [error message is the same]
3. Submit Request
4. Job scheduled
5. See error on back end/ See error on failed jobs.

**Expected behavior**
I would really like it to complete the job successfully -even a temp solution.

**Screenshots**
Error message in the console is listed as:
![ISSUE](https://github.com/f0cker/crackq/assets/59946245/a3db8ffb-c032-4f8e-81bf-2443568795a4)

**Additional context**
This was an upgrade from 0.1.0 -> 0.1.1 -> 0.1.2. 0.1.1 Never worked for me due to the library issues.

**Comment by f0cker** [comment]
Thanks for reporting this. What command are you using to run compose? It looks like an nvidia runtime issue so it's not seeing the cards within the docker containers. I updated the install steps on the Wiki, did you reinstall docker/compose/nvidia runtime?

**Comment by f0cker** [comment]
While the containers are up, you can run the following to check the crackq container is able to the GPU cards:

`sudo docker exec -it crackq nvidia-smi`

`sudo docker exec -it crackq /opt/crackq/build/pyhashcat/pyhashcat/hashcat/hashcat -b -m 1000`

**Comment by f0cker** [comment]
Did you remove the old docker containers/images? I have the following confirmed working on a test AWS box:
`
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    Off | 00000000:00:1E.0 Off |                    0 |
|  0%   27C    P0              53W / 300W |      4MiB / 23028MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+`

Maybe try reinstalling now that the drivers are updated? 

run this beforehand:
`sudo docker system prune --all`
**This will wipe all containers so do them individually if you have other containers on your server ;)

**Comment by f0cker** [comment]
I don't think you need to reinstall the OS. It's something around this error:
`cuInit(): forward compatibility was attempted on non supported HW`

I'll do some digging when I have time, but in the meantime here's all the version info from my test box:

```
sudo docker --version
Docker version 24.0.7, build afdd53b

Host driver version:

nvidia-smi
Mon Jan 22 10:20:52 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+

Container driver version:

sudo docker exec -it crackq nvidia-smi
Mon Jan 22 10:19:13 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+

nvidia-container-runtime --version
NVIDIA Container Runtime version 1.13.5
commit: 6b8589dcb4dead72ab64f14a5912886e6165c079
spec: 1.1.0-rc.2

runc version 1.1.10
commit: v1.1.10-0-g18a0cb0
spec: 1.0.2-dev
go: go1.20.12
libseccomp: 2.5.3

nvidia-container-toolkit -version
NVIDIA Container Runtime Hook version 1.13.5
commit: 6b8589dcb4dead72ab64f14a5912886e6165c079
```

**Comment by f0cker** [comment]
Where did you install the Nvidia driver from, direct download or from a repo? Latest version should be 535.154.05 for RTX I believe

**Comment by f0cker** [comment]
Yeah try removing the driver and installing the latest from Nvidia: https://www.nvidia.com/Download/index.aspx

**Comment by f0cker** [comment]
It's a shame I can't reproduce this to debug myself, I've tried 3 different Nvidia GPU models in AWS which all work fine. So I think it's specific to GTX/RTX models, but would be good to know if anyone else has been able to get these models working with the latest version of crackq. If you're willing to try, since it's an issue on the Nvidia/docker side, my next step would be trying different docker images to the one I've setup. 

So, within this file: ./docker/nvidia/ubuntu/Dockerfile

On line 1 replace the image name with one of the following and rebuild and test, then try others if no good:

FROM nvidia/cuda:12.2.2-devel-ubuntu20.04
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04
FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04
FROM nvidia/cuda:12.2.2-runtime-ubuntu20.04

**Comment by f0cker** [comment]
That's awesome, thanks for taking the time to help me debug this. I'll rollback the image version and push an update soon.
